name: yundera
services:
  main_app:
    image: nginx:1.15.0
    hostname: admin
    container_name: admin
    restart: unless-stopped
    expose:
      - "80"
    networks:
      pcs: null

  mesh-router:
    image: nasselle/mesh-router:latest
    restart: unless-stopped
    hostname: mesh-router
    container_name: mesh-router
    # necessary conf for wireguard
    # https://hub.docker.com/r/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Enable IPv4 forwarding
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PROVIDER=https://nsl.sh,EkGcLEimm9TIa5TdketObbnbRQ52@nasselle.com,k1k5dy2ydthiaa4zpp3skaydo1dmcoovqi3ahlckiundmc5k0jv753m4c4adfu4i9rqmesfzba5o7czapiksualxfg9kvhd49ekg
    networks:
      - pcs

  casaos:
    image: nasselle/casa-img:latest
    hostname: casaos
    container_name: casaos
    restart: unless-stopped
    environment:
      - DATA_ROOT=/DATA
      - REF_NET=pcs
      - REF_DOMAIN=wiseferret.nsl.sh
      - REF_SCHEME=https
      - REF_PORT=443
    volumes:
      - /DATA:/DATA
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pcs

networks:
  pcs:
    name: pcs

x-casaos:
  author: self
  category: self
  hostname: admin-wiseferret.nsl.sh
  icon: https://styles.redditmedia.com/t5_deqw76/styles/communityIcon_mrihspifrgee1.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: yundera
  title:
    custom: Yundera