version: '3.8'

services:
  settings-app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: settings-dev
    env_file:
      - dev-env
    ports:
      - "4342:80"
    volumes:
      - ssh_keys:/host_ssh/
      - data:/app/data/
    environment:
      - HOST_ADDRESS=ubuntu-server
    networks:
      - app-network
    depends_on:
      - ubuntu-host-pcs

  #PCS emulation
  ubuntu-host-pcs:
    build:
      context: ../../
      dockerfile: /dev/run/Dockerfile
    container_name: ubuntu-host-pcs
    hostname: ubuntu-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh_keys:/root/.ssh/
      - data:/DATA/AppData/casaos/apps/yundera/
      - ../../template-setup/root/:/tmp/setup:ro
      - ./dev-env:/tmp/.env:ro
    command: >
      bash -c "
            mkdir -p /DATA/AppData/casaos/apps/yundera/
            cp -v -r /tmp/setup/* /DATA/AppData/casaos/apps/yundera/ &&
            cp -v /tmp/.env /DATA/AppData/casaos/apps/yundera/.env &&
            chmod +x /DATA/AppData/casaos/apps/yundera/scripts/os-init/os-init.sh &&
            /DATA/AppData/casaos/apps/yundera/scripts/os-init/os-init.sh &&
            service ssh start &&
            tail -f /dev/null
          "
    networks:
      - app-network

volumes:
  ssh_keys:
  data:

networks:
  app-network:
    driver: bridge